version: "3.3"

services:

  # http://serveis.bcn.coop
  coopolis:
    container_name: ateneu_coopolis
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_production
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8000:8000
    depends_on:
      - db
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  # http://ateneu-demo.codi.coop
  ateneu-demo:
    container_name: ateneu_demo
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-demo
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8001 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8001:8001
    depends_on:
      - db

  # https://serveis.coopcamp.cat
  ateneu-coopcamp:
    container_name: ateneu_coopcamp
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopcamp
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8002 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8002:8002
    depends_on:
      - db

  # https://serveis.coopmaresme.cat
  ateneu-coopmaresme:
    container_name: ateneu_coopmaresme
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopmaresme
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8003 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8003:8003
    depends_on:
      - db

  # https://serveis.ateneubnord.cat
  ateneu-bnord:
    container_name: ateneu_bnord
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-bnord
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8004 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8004:8004
    depends_on:
      - db

  # https://serveis.ponentcoopera.cat
  # Ens saltem el port 8005 perquè hi ha l'antic back-office (java) allà.
  ateneu-ponentcoopera:
    container_name: ateneu_ponentcoopera
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-ponentcoopera
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8006 --timeout 300
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8006:8006
    depends_on:
      - db

  # https://serveis.ateneucooperatiuvalles.org
  ateneu-vallesoccidental:
    container_name: ateneu_vallesoccidental
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-vallesoccidental
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8007
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8007:8007
    depends_on:
      - db

  # https://serveis.coopcatcentral.cat
  ateneu-catcentral:
    container_name: ateneu_catcentral
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-catcentral
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    ports:
      - 8008:8008
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    volumes:
      - /srv/postgres-data/coopolis-production:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword