# Generated by Django 3.2.14 on 2022-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0059_entity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='organizer_reminded',
            field=models.DateTimeField(blank=True, null=True, verbose_name="data d'enviament de recordatori a responsable"),
        ),
    ]
