# Generated by Django 3.2.14 on 2022-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0061_activityfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='poll_reminder_body',
            field=models.TextField(blank=True, help_text='Aquest text s\'inclourà al correu de recordatori. És molt important que el formateig del text sigui el menor possible, i en particular, que si copieu i enganxeu el text d\'algun altre lloc cap aquí, ho feu amb l\'opció "enganxar sense format", ja que sinó arrossegarà molta informació de formateig que probablement farà que el correu es vegi malament.', null=True, verbose_name="Cos del correu de recordatori d'omplir l'enquesta"),
        ),
    ]
