# Generated by Django 3.2.14 on 2022-09-06 08:57

from django.db import migrations
from django.urls import reverse


def populate_resrvations_urls(apps, schema_editor):
    print('')
    activity_model = apps.get_model("cc_courses", "Activity")
    activities = activity_model.objects.filter(
        room_reservation__isnull=False,
    )
    for activity in activities:
        activity.room_reservation.url = admin_url(activity.id)
        activity.room_reservation.save()
        print(f"Reserva de sala de: {activity.name=} ara conté la URL "
              f"{activity.room_reservation.url=}")


def admin_url(activity_id):
    return reverse(
        "admin:cc_courses_activity_change",
        kwargs={'object_id': activity_id},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cc_courses", "0062_activity_poll_reminder_body"),
    ]

    operations = [
        migrations.RunPython(populate_resrvations_urls),
    ]
