# Generated by Django 3.2.14 on 2022-09-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0008_auto_20220907_0934'),
        ('cc_courses', '0063_data_reservations_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='cc_courses.activity', verbose_name='activitat')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='facilities_reservations.equipment', verbose_name='equipament')),
            ],
            options={
                'verbose_name': 'equipament de la sessió',
                'verbose_name_plural': 'equipaments de les sessions',
            },
        ),
    ]
