# Generated by Django 3.2.14 on 2022-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0007_equipment_reservationequipment'),
        ('cc_courses', '0063_data_reservations_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='equipments',
            field=models.ManyToManyField(blank=True, to='facilities_reservations.Equipment', verbose_name='equipaments'),
        ),
    ]
