# Generated by Django 3.2.14 on 2022-09-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0008_auto_20220907_0934'),
        ('cc_courses', '0064_activityequipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityequipment',
            unique_together={('equipment', 'activity')},
        ),
    ]
