# Generated by Django 3.2.14 on 2023-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0065_auto_20230831_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='A càrrec de'),
        ),
    ]
