# Generated by Django 3.2.14 on 2022-09-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0008_auto_20220907_0934'),
        ('cc_courses', '0065_alter_activityequipment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='cc_courses.ActivityEquipment', to='facilities_reservations.Equipment', verbose_name='equipaments'),
        ),
        migrations.AlterField(
            model_name='activityequipment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc_courses.activity', verbose_name='activitat'),
        ),
        migrations.AlterField(
            model_name='activityequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_reservations.equipment', verbose_name='equipament'),
        ),
    ]
