# Generated by Django 3.2.14 on 2024-03-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0067_auto_20240226_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='aimed_at',
            field=models.TextField(default='', verbose_name='adreçat a'),
        ),
    ]
