# Generated by Django 3.2.14 on 2024-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0068_alter_course_aimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='exclude_from_justification',
            field=models.BooleanField(default=False, verbose_name="No incloure a l'excel de justificació"),
        ),
    ]
