# Generated by Django 3.2.14 on 2024-04-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0067_alter_activity_sub_service'),
        ('cc_courses', '0069_activity_exclude_from_justification'),
    ]

    operations = [
    ]
