# Generated by Django 2.2.7 on 2020-08-07 07:45

from django.db import migrations


def populate_mail_templates(apps, schema_editor):
    print('')
    mail_model = apps.get_model('mailing_manager', 'Mail')

    obj, created = mail_model.objects.update_or_create(
        text_identifier='EMAIL_ACTIVITY_RESPONSIBLE_REMINDER',
        defaults={
            'text_identifier': 'EMAIL_ACTIVITY_RESPONSIBLE_REMINDER',
            'subject': "Recordatori: d'aquí {number_days} dies hi ha: {activity_name}",
            'body': """<p><strong>
    Reps aquest recordatori com a persona responsable de la formació.
</strong></p>
<p style="padding-top: 20px">
    El backoffice té la funcionalitat d'enviar un recordatori a 
    totes les persones inscrites, però cal executar aquest enviament de forma
    manual ja que abans de fer-ho convé tenir les instruccions i material
    configurats a la fitxa de la sessió, així com revisar les dades i el
    llistat de persones inscrites.
</p>
<p style="padding-top: 20px">
    <a href="{absolute_url_admin_activity}">Enllaç a l'activitat</a>
</p>
            """,
            'default_template_path': 'emails/front_single_text.html'
        },
    )
    print('EMAIL_ACTIVITY_RESPONSIBLE_REMINDER template updated.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0099_projectstage_sub_service'),
    ]

    operations = [
        # migrations.RunPython(populate_mail_templates),
    ]
