# Generated by Django 3.2.14 on 2022-07-29 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0100_datamigration_activity_responsible_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagesession',
            name='involved_partners',
            field=models.ManyToManyField(blank=True, help_text="Persones que apareixeran a la justificació com a que han participat a la sessió d'acompanyament.", related_name='stage_sessions_participated', to=settings.AUTH_USER_MODEL, verbose_name='persones involucrades'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='involved_partners',
            field=models.ManyToManyField(blank=True, help_text="Persones que apareixeran a la justificació com a que han participat a l'acompanyament.", related_name='stage_involved_partners', to=settings.AUTH_USER_MODEL, verbose_name='(obsolet) Persones involucrades'),
        ),
    ]
