# Generated by Django 3.2.14 on 2022-08-03 12:30

import apps.coopolis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0102_data_move_involved_partners_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagesession',
            name='justification_file',
            field=models.FileField(blank=True, null=True, storage=apps.coopolis.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='fitxer de justificació'),
        ),
    ]
