# Generated by Django 2.2.7 on 2021-09-08 14:54
import re

from django.db import migrations


def custom_replace(original_string, target_string, replacement_string):
    """
    Replace the string if it's not preceded by a < or a double quote char and
    it's also not followed by a > or a double quote char.
    That way if the code gets executed multiple times, it will not keep
    stacking replacements of <a> tags inside each other.

    :param original_string:
    :param target_string:
    :param replacement_string:
    :return: string
    """
    pattern = r'(?<![">])' + re.escape(target_string) + r'(?!(?:<\/a>|"))'
    modified_string = re.sub(
        pattern,
        replacement_string,
        original_string,
        flags=re.DOTALL,
    )
    return modified_string


def fix_mail_urls(apps, schema_editor):
    print('')
    mail_model = apps.get_model('mailing_manager', 'Mail')

    obj = mail_model.objects.get(text_identifier="EMAIL_PASSWORD_RESET")
    obj.body = custom_replace(
        obj.body,
        "{password_reset_url}",
        "<a href=\"{password_reset_url}\">{password_reset_url}</a>",
    )
    obj.save()
    print('EMAIL_PASSWORD_RESET URLs in template fixed.')

    obj = mail_model.objects.get(text_identifier="EMAIL_ENROLLMENT_POLL")
    # In this case, replacing the full line to avoid having to fine tune the
    # reg exp.
    obj.body = custom_replace(
        obj.body,
        '<p style="padding-top: 20px">{absolute_url_activity}</p>',
        """
        <p style="padding-top: 20px">
            <a href=\"{absolute_url_activity}\">{absolute_url_activity}</a>
        </p>
        """,
    )
    obj.save()
    print('EMAIL_ENROLLMENT_POLL URLs in template fixed.')

    obj = mail_model.objects.get(text_identifier="EMAIL_SIGNUP_WELCOME")
    obj.body = custom_replace(
        obj.body,
        "{url_backoffice}",
        '<a href=\"{url_backoffice}\">{url_backoffice}</a>',
    )
    obj.save()
    print('EMAIL_SIGNUP_WELCOME URLs in template fixed.')


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0105_auto_20230831_1117'),
    ]

    operations = [
        # migrations.RunPython(fix_mail_urls),
    ]
