# Generated by Django 3.2.14 on 2023-10-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0020_alter_subsidyperiod_name'),
        ('coopolis', '0108_data_created_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'comarca',
                'verbose_name_plural': 'comarques',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectsConstituted',
        ),
        migrations.AlterModelOptions(
            name='createdentity',
            options={'verbose_name': 'Entitat creada', 'verbose_name_plural': 'Entitats creades'},
        ),
        migrations.AlterField(
            model_name='project',
            name='subsidy_period',
            field=models.ForeignKey(blank=True, help_text="Anteriorment es feia servir aquest camp per saber quins projectes incloure a la justificació com a Constituïts. Ara això es fa des de l'apartat Entitats Creades.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataexports.subsidyperiod', verbose_name='(OBSOLET) Convocatòria de la constitució'),
        ),
    ]
