# Generated by Django 3.2.14 on 2023-10-05 10:59
import json
from urllib.request import urlopen

from django.db import migrations


def import_county_data(apps, schema_editor):
    county_model = apps.get_model("coopolis", "County")
    counties_source = "https://analisi.transparenciacatalunya.cat/resource/gsjn-sema.json"

    counties = json.loads(urlopen(counties_source).read())
    county_model.objects.all().delete()
    for county in counties:
        obj = county_model.objects.create(
            id=int(county["codi"]),
            name=county["nom"],
        )
        print(f"Creada comarca: {obj.name}")


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0109_auto_20231005_1258'),
    ]

    operations = [
        migrations.RunPython(import_county_data),
    ]
