# Generated by Django 3.2.14 on 2023-10-05 10:59
from django.db import migrations

counties = [
    {"codi": "01", "nom": "Alt Camp"}
    , {"codi": "02", "nom": "Alt Empordà"}
    , {"codi": "03", "nom": "Alt Penedès"}
    , {"codi": "04", "nom": "Alt Urgell"}
    , {"codi": "05", "nom": "Alta Ribagorça"}
    , {"codi": "06", "nom": "Anoia"}
    , {"codi": "07", "nom": "Bages"}
    , {"codi": "08", "nom": "Baix Camp"}
    , {"codi": "09", "nom": "Baix Ebre"}
    , {"codi": "10", "nom": "Baix Empordà"}
    , {"codi": "11", "nom": "Baix Llobregat"}
    , {"codi": "12", "nom": "Baix Penedès"}
    , {"codi": "13", "nom": "Barcelonès"}
    , {"codi": "14", "nom": "Berguedà"}
    , {"codi": "15", "nom": "Cerdanya"}
    , {"codi": "16", "nom": "Conca de Barberà"}
    , {"codi": "17", "nom": "Garraf"}
    , {"codi": "18", "nom": "Garrigues"}
    , {"codi": "19", "nom": "Garrotxa"}
    , {"codi": "20", "nom": "Gironès"}
    , {"codi": "21", "nom": "Maresme"}
    , {"codi": "22", "nom": "Montsià"}
    , {"codi": "23", "nom": "Noguera"}
    , {"codi": "24", "nom": "Osona"}
    , {"codi": "25", "nom": "Pallars Jussà"}
    , {"codi": "26", "nom": "Pallars Sobirà"}
    , {"codi": "27", "nom": "Pla d'Urgell"}
    , {"codi": "28", "nom": "Pla de l'Estany"}
    , {"codi": "29", "nom": "Priorat"}
    , {"codi": "30", "nom": "Ribera d'Ebre"}
    , {"codi": "31", "nom": "Ripollès"}
    , {"codi": "32", "nom": "Segarra"}
    , {"codi": "33", "nom": "Segrià"}
    , {"codi": "34", "nom": "Selva"}
    , {"codi": "35", "nom": "Solsonès"}
    , {"codi": "36", "nom": "Tarragonès"}
    , {"codi": "37", "nom": "Terra Alta"}
    , {"codi": "38", "nom": "Urgell"}
    , {"codi": "39", "nom": "Aran"}
    , {"codi": "40", "nom": "Vallès Occidental"}
    , {"codi": "41", "nom": "Vallès Oriental"}
    , {"codi": "42", "nom": "Moianès"}
    , {"codi": "43", "nom": "Lluçanès"}
    , {"codi": "98", "nom": "No consta"}
    , {"codi": "99", "nom": "Altres/Diversos"}
]


def import_county_data(apps, schema_editor):
    county_model = apps.get_model("coopolis", "County")
    # Source: https://analisi.transparenciacatalunya.cat/resource/gsjn-sema.json

    county_model.objects.all().delete()
    for county in counties:
        obj = county_model.objects.create(
            id=int(county["codi"]),
            name=county["nom"],
        )
        print(f"Creada comarca: {obj.name}")


class Migration(migrations.Migration):
    dependencies = [
        ('coopolis', '0109_auto_20231005_1258'),
    ]

    operations = [
        migrations.RunPython(import_county_data),
    ]
