# Generated by Django 3.2.14 on 2023-10-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0110_data_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coopolis.county'),
        ),
        migrations.AddField(
            model_name='town',
            name='name_for_justification',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='nom'),
        ),
    ]
