# Generated by Django 3.2.14 on 2024-02-20 10:41

import apps.coopolis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0111_auto_20231005_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, default='', help_text='Clica per carregar una imatge', max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='imatge del projecte'),
        ),
        migrations.AlterField(
            model_name='town',
            name='name_for_justification',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='nom per la justificació'),
        ),
    ]
