# Generated by Django 3.2.14 on 2023-11-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc_courses', '0066_activity_teacher'),
        ('coopolis', '0112_auto_20231006_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinsertion',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cc_courses.activity'),
        ),
        migrations.AlterField(
            model_name='employmentinsertion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment_insertions', to='coopolis.project', verbose_name='projecte acompanyat'),
        ),
    ]
