# Generated by Django 3.2.14 on 2024-02-22 11:56

import apps.coopolis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0113_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstagesession',
            name='file1',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='material adjunt'),
        ),
        migrations.AddField(
            model_name='projectstagesession',
            name='file2',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='material adjunt'),
        ),
        migrations.AddField(
            model_name='projectstagesession',
            name='file3',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='material adjunt'),
        ),
        migrations.AddField(
            model_name='projectstagesession',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='objectiu de la sessió'),
        ),
        migrations.AddField(
            model_name='projectstagesession',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='retorn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('OTHER', 'Altre'), ('FEMALE', 'Dona'), ('MALE', 'Home')], default='', max_length=10, verbose_name='gènere'),
        ),
    ]
