# Generated by Django 3.2.14 on 2024-02-26 13:01

import apps.coopolis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0114_auto_20240222_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='stage_state',
            field=models.CharField(blank=True, choices=[('OPEN', 'Obert'), ('CLOSE', 'Tancat')], default='', max_length=8, null=True, verbose_name="estat de l'acompanyament"),
        ),
        migrations.AlterField(
            model_name='projectstagesession',
            name='file2',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='projectstagesession',
            name='file3',
            field=models.FileField(blank=True, max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name=''),
        ),
    ]
