# Generated by Django 3.2.14 on 2024-02-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0113_auto_20231107_1142'),
        ('coopolis', '0115_auto_20240226_1401'),
    ]

    operations = [
    ]
