# Generated by Django 3.2.14 on 2024-02-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0114_merge_0113_auto_20231107_1142_0113_user_photo'),
        ('coopolis', '0117_auto_20240226_1549'),
    ]

    operations = [
    ]
