# Generated by Django 3.2.14 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0118_merge_20240227_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_state',
            field=models.CharField(choices=[('PENDING', 'En procés'), ('OPEN', 'Sol·licitat'), ('CLOSE', 'Finalizat')], default=None, max_length=8, null=True, verbose_name="estat de l'acompanyament"),
        ),
    ]
