# Generated by Django 3.2.14 on 2024-02-29 09:04

import apps.coopolis.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0119_auto_20240227_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='stage_state',
            field=models.CharField(choices=[(None, 'Sense indicar'), ('PENDING', 'Sol·licitat'), ('OPEN', 'En procés'), ('CLOSE', 'Finalizat')], default=None, max_length=8, null=True, verbose_name="estat de l'acompanyament"),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default='', help_text='Clica per carregar una imatge', max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='fotografia'),
        ),
    ]
