# Generated by Django 3.2.14 on 2024-03-06 15:40

import apps.coopolis.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0120_auto_20240229_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, default='', help_text='Clica per carregar una imatge', max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='imatge del projecte'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_state',
            field=models.CharField(blank=True, choices=[(None, 'Sense indicar'), ('PENDING', 'Sol·licitat'), ('OPEN', 'En procés'), ('CLOSE', 'Finalitzat')], default=None, max_length=8, null=True, verbose_name="estat de l'acompanyament"),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default='', help_text='Clica per carregar una imatge', max_length=250, null=True, storage=apps.coopolis.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='fotografia'),
        ),
    ]
