# Generated by Django 3.2.14 on 2024-04-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0123_auto_20240419_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subsidy_period',
        ),
    ]
