# Generated by Django 3.2.14 on 2024-04-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0124_remove_project_subsidy_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='name_for_justification',
        ),
    ]
