# Generated by Django 3.2.14 on 2024-04-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0114_auto_20231109_1259'),
        ('coopolis', '0125_remove_town_name_for_justification'),
    ]

    operations = [
    ]
