# Generated by Django 3.2.14 on 2024-06-03 14:52

from django.db import migrations


def update_town_name(apps, schema_editor):
    print('')
    town_model = apps.get_model("coopolis", "Town")
    try:
        sta_maria_corco = town_model.objects.get(name="SANTA MARIA DE CORCO")
    except town_model.DoesNotExist:
        print("ATENCIÓ: No existeix la població SANTA MARIA DE CORCO")
        return

    sta_maria_corco.name = "Santa Maria de Corcó"
    sta_maria_corco.save()

    print("Fet: nom de la població 'SANTA MARIA DE CORCO' rectificat.")


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0128_data_id_number_type'),
    ]

    operations = [
        migrations.RunPython(update_town_name),
    ]
