# Generated by Django 3.2.14 on 2024-06-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0129_data_sta_ma_corco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='follow_up_situation',
            field=models.CharField(blank=True, choices=[('PENDENT', 'Pendent d’enviar proposta de trobada'), ('ENVIAT', 'Enviat email amb proposta de data per trobar-nos'), ('CONCERTADA', 'Data de trobada concertada'), ('ACOLLIT', 'Acollida realitzada'), ('EN_CURS', 'Acompanyament en curs'), ('PAUSA', 'Acompanyament en pausa'), ('CANCEL', 'Acompanyament cancel·lat')], max_length=50, null=True, verbose_name='seguiment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cannot_share_id',
            field=models.BooleanField(default=False, verbose_name='Obsolet'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualització')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='coopolis.project', verbose_name='projecte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='usuari')),
            ],
            options={
                'verbose_name': 'invitació',
                'verbose_name_plural': 'invitacions',
                'ordering': ['created'],
            },
        ),
    ]
