# Generated by Django 3.2.14 on 2024-06-25 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0130_auto_20240605_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(help_text="Si degut a la teva situació legal et suposa un inconvenient indicar el DNI, selecciona 'No puc donar el DNI' a Tipus de Document.", max_length=11, null=True, verbose_name='DNI/NIE/Passaport'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualització')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='coopolis.project', verbose_name='projecte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='usuari')),
            ],
            options={
                'verbose_name': 'invitació',
                'verbose_name_plural': 'invitacions',
                'ordering': ['created'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
