# Generated by Django 3.2.14 on 2024-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coopolis', '0131_data_email_project_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(help_text="Si degut a la teva situació legal et suposa un inconvenient indicar el DNI, selecciona 'No puc donar el DNI' a Tipus de Document.", max_length=11, null=True, verbose_name='DNI/NIE/Passaport'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('user', 'project')},
        ),
    ]
