# Generated by Django 3.2.14 on 2022-09-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0006_alter_room_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('storing_place', models.CharField(max_length=250, verbose_name='on es desa')),
            ],
            options={
                'verbose_name': 'equipament',
                'verbose_name_plural': 'equipaments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facilities_reservations.equipment', verbose_name='equipament')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='facilities_reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'equipament de la reserva',
                'verbose_name_plural': 'equipaments de les reserves',
                'unique_together': {('equipment', 'reservation')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmada'),
        ),
    ]
