# Generated by Django 3.2.14 on 2022-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities_reservations', '0007_equipment_reservationequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storing_place',
            field=models.CharField(max_length=250, verbose_name='on es desa'),
        ),
    ]
