version: "3.3"

services:
  coopolis:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_develop
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
    depends_on:
      - db
    #entrypoint: ["sh", "-c", "sleep 2073600"]
  db:
    image: postgres
    volumes:
      - /srv/postgres-data/coopolis-develop:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/srv
    ports:
      - 80:80
    depends_on:
      - coopolis
