version: "3.3"

services:

  # http://coopolis-develop.codi.coop
  coopolis:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_develop
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
    depends_on:
      - db
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  # http://ateneu-demo.codi.coop
  segon_ateneu:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.segon_ateneu
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/srv
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - /srv/postgres-data/coopolis-develop2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../:/srv
    ports:
      - 8002:80
    depends_on:
      - coopolis
      - segon_ateneu