version: "3.5"

networks:
  develop_ateneus:
    name: develop_ateneus

services:

  # http://coopolis-develop.codi.coop
  ateneu-coopolis:
    container_name: develop_ateneus_coopolis # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.ateneu-coopolis
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:5001 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
    networks:
      - develop_ateneus
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  db:
    container_name: develop_coopolis_db
    image: postgres:11
    volumes:
      - /srv/postgres-data/coopolis-develop2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - develop_ateneus

  nginx:
    container_name: develop_coopolis_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../:/srv
    ports:
      - 5001-5013
    depends_on:
      - coopolis
    networks:
      - develop_ateneus

  ofelia:
    container_name: develop_coopolis_ofelia
    image: 'mcuadros/ofelia:latest'
    volumes:
      - ./ofelia/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - coopolis
      - segon_ateneu
    networks:
      - develop_ateneus
