version: "3.3"

services:

  # http://coopolis-develop.codi.coop
  coopolis:
    container_name: develop_coopolis_app # If changed, update ofelia config
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.server_develop
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db
    #entrypoint: ["sh", "-c", "sleep 2073600"]

  # http://segon_ateneu-develop.codi.coop
  segon_ateneu:
    container_name: develop_coopolis_segon_ateneu
    build:
      context: ..
      dockerfile: ./docker-develop/Dockerfile
    environment:
      - DB_HOST=db
      - "PYTHONUNBUFFERED=1"
      - DJANGO_SETTINGS_MODULE=coopolis_backoffice.settings.segon_ateneu
      - PYTHONPATH=/shared_libraries
    command: gunicorn coopolis_backoffice.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../:/srv
      - ../../python_shared_libraries/:/shared_libraries
    depends_on:
      - db

  db:
    container_name: develop_coopolis_db
    image: postgres:11
    volumes:
      - /srv/postgres-data/coopolis-develop2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  nginx:
    container_name: develop_coopolis_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - ../:/srv
    ports:
      - 8002:80
    depends_on:
      - coopolis
      - segon_ateneu

  ofelia:
    container_name: esguard_dev_ofelia
    image: 'mcuadros/ofelia:latest'
    volumes:
      - ./ofelia/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - coopolis
      - segon_ateneu