# Generated by Django 5.1.4 on 2025-01-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0020_alter_subsidyperiod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('subsidy_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataexports.subsidyperiod', verbose_name='convocatòria')),
            ],
            options={
                'verbose_name': 'servei',
                'verbose_name_plural': 'serveis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataexports.service', verbose_name='servei')),
            ],
            options={
                'verbose_name': 'eix',
                'verbose_name_plural': 'eixos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubSubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nom')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataexports.subservice', verbose_name='eix')),
            ],
            options={
                'verbose_name': 'actuació',
                'verbose_name_plural': 'actuacions',
                'ordering': ['name'],
            },
        ),
    ]
