# Generated by Django 2.2.7 on 2020-08-07 14:02

from django.db import migrations


def fill_service_subservice_subsubservice(apps, schema_editor):
    print('')
    subsidy_period_model = apps.get_model("dataexports", "SubsidyPeriod")
    service_model = apps.get_model("dataexports", "Service")
    subservice_model = apps.get_model("dataexports", "SubService")
    subsubservice_model = apps.get_model("dataexports", "SubSubService")
    period_obj = subsidy_period_model.objects.get(name="2024-2025")

    data = [
        {
            "name": "Servei 1 - divulgació, sensibilització i generació de coneixement",
            "subservices": [
                {
                    "name": "Extensió del cooperativisme i l’ESS",
                    "subsubservices": [
                        {"name": "1.1. Campanya de comunicació i difusió per l'extensió del cooperativisme i l'ESS"},
                        {"name": "1.3. Accions de sensibilització i/o dinamització pròpies"},
                        {"name": "1.4. Accions educatives a estudiants d'estudis professionalitzadors (FPs, Noves Oportunitats, PFIs i PTTs, Universitats...)"},
                        {"name": "1.5. Transversalització de l'ESS i el cooperativisme en l'àmbit educatiu"},
                        {"name": "1.6. Elaboració de recursos sobre cooperativisme i ESS"},
                        {"name": "1.7 Participació en accions d'altres agents del territori: jornades, fires, programes i publicacions"},
                    ]
                },
                {
                    "name": "Acompanyament a la generació d’ocupació",
                    "subsubservices": [
                        {"name": "1.2. Campanya de comunicació i difusió adreçada a donar a conèixer els serveis de l'ateneu i/o cercles"},
                        {"name": "1.8 Concursos/premis per a la creació de noves cooperatives"},
                    ]
                },
                {
                    "name": "Respondre a les necessitats o especificitats del territori",
                    "subsubservices": [
                        {"name": "1.9 Accions de sensibilització i/o dinamització amb altres agents del territori"},
                    ]
                },
            ],
        },
        {
            "name": "Servei 2 - Formació per a la promoció, creació i consolidació de cooperatives i projectes d'ESS",
            "subservices": [
                {
                    "name": "Acompanyament a la generació d’ocupació",
                    "subsubservices": [
                        {"name": "2.1. Accions de formació bàsica a persones emprenedores o entitats interessades en la fòrmula cooperativa i altres formes de l'ESS generadores d'ocupació"},
                    ]
                },
                {
                    "name": "Extensió del cooperativisme i l’ESS",
                    "subsubservices": [
                        {"name": "2.2. Accions formatives sobre cooperativisme o aprofundiment i especialització per membres de cooperatives i altres entitats de l'ESS no generadores d'ocupació"},
                        {"name": "2.3. Accions de formació per a prescriptores de l'ESS"},
                    ]
                },
                {
                    "name": "Acompanyament a la generació d’ocupació",
                    "subsubservices": [
                        {"name": "2.4. Accions de formació per a la consolidació i al creixement de cooperatives i altres organitzacions d'ESS generadores d'ocupació"},
                    ]
                },
                {
                    "name": "Respondre a les necessitats o especificitats del territori",
                    "subsubservices": [
                        {"name": "2.5 Coordinació amb estratègies de formació territorial i col·laboració amb altres agents"},
                    ]
                },
            ],
        },
        {
            "name": "Servei 3 - d'acompanyament per a la creació i consolidació de cooperatives i projectes d'ESS",
            "subservices": [
                {
                    "name": "Acompanyament a la generació d’ocupació",
                    "subsubservices": [
                        {"name": "3.1 Acompanyament a la creació de cooperatives i altres organitzacions d'ESS generadores d'ocupació"},
                        {"name": "3.3 Acompanyament a la consolidació i creixement de cooperatives generadores d'ocupació"},
                        {"name": "3.5 Acompanyament a la transformació i/o relleu de cooperatives i altres entitats de l'ESS"},
                        {"name": "3.8 Coordinació amb estratègies de polítiques actives d'ocupació territorial i col·laboració amb altres agents"},
                    ]
                },
                {
                    "name": "Extensió del cooperativisme i l’ESS",
                    "subsubservices": [
                        {"name": "3.2 Acompanyament a la creació de cooperatives i altres formes jurídiques de l'ESS no generadores d'ocupació"},
                        {"name": "3.4 Acompanyament a la consolidació i creixement de cooperatives i altres entitats de l'ESS no generadores d'ocupació"},
                    ]
                },
                {
                    "name": "Acompanyament a altres programes d’economia social i altres programes públics",
                    "subsubservices": [
                        {"name": "3.6 Acompanyament a projectes d'intercooperació "},
                    ]
                },
                {
                    "name": "Respondre a les necessitats o especificitats del territori",
                    "subsubservices": [
                        {"name": "3.7 Acompanyament al tancament de cooperatives i entitats de l'ESS"},
                    ]
                },
            ],
        },
        {
            "name": "Servei 4 - treball en xarxa i dinamització territorial",
            "subservices": [
                {
                    "name": "Respondre a les necessitats o especificitats del territori",
                    "subsubservices": [
                        {"name": "4.1 Diagnosi sobre les mancances i oportunitats socioeconòmiques i projecció estratègica territorial a 3 anys vista"},
                        {"name": "4.2 Generació d'espais estratègics a nivell sectorial o territorial amb entitats de l'ESS del territori o ens locals"},
                        {"name": "4.3. Interlocució amb les entitats de l'ESS del territori d'abast de l'AC"},
                        {"name": "4.4 Interlocució amb els òrgans municipals i supramunicipals del territori d'abast de l'AC "},
                        {"name": "4.5 Participació d'espais o plans estratègics de desenvolupament local i sectorial"},
                    ]
                },
                {
                    "name": "Coordinació amb altres programes d’economia social i altres programes públics",
                    "subsubservices": [
                        {"name": "4.6 Representació i participació en sessions informatives amb agents transversals locals i territorials"},
                        {"name": "4.7 Coordinació amb la resta de programes de l'ES del territori"},
                    ]
                },
                {
                    "name": "Extensió del cooperativisme i l’ESS",
                    "subsubservices": [
                        {"name": "4.8 Treball en xarxa amb altres ateneus: assistir a reunions i col·laborar en iniciatives conjuntes."},
                    ]
                },
            ],
        },
        {
            "name": "Serveis complementaris",
            "subservices": [
                {
                    "name": "Serveis complementaris",
                    "subsubservices": [
                        {"name": "5.1 Serveis Complementaris"},
                    ]
                },
            ],
        },
    ]

    for service_data in data:
        service_obj = service_model.objects.create(
            name=service_data["name"],
            subsidy_period=period_obj,
        )

        for subservice_data in service_data["subservices"]:
            subservice_obj = subservice_model.objects.create(
                name=subservice_data["name"],
                service=service_obj,
            )

            for subsubservice_data in subservice_data["subsubservices"]:
                subsubservice_obj = subsubservice_model.objects.create(
                    name=subsubservice_data["name"],
                    subservice=subservice_obj,
                )
                print(f"Created: subservice {subsubservice_obj.name} / {subservice_obj.name} / {service_obj.name}")

    print("Service, SubService and SubSubService updated.")


class Migration(migrations.Migration):

    dependencies = [
        ('dataexports', '0021_service_subservice_subsubservice'),
    ]

    operations = [
        migrations.RunPython(fill_service_subservice_subsubservice),
    ]
